import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route } from 'react-router-dom';
import Home from './pages/Home';
import Login from './pages/Login';
import SignUpSelection from './pages/SignUpSelection';
import StudentSignUp from './pages/StudentSignUp';
import ProfessorSignUp from './pages/ProfessorSignUp';
import Otp from './pages/Otp';
import Application from './pages/Application';
import Team from './pages/Team';
import DashboardLayout from './pages/components/DashboardLayout';
import Progress from './pages/Progress';
import Training from './pages/Training';
import ResetPassword from './pages/ResetPassword';
import ForgotPassword from './pages/forgot_password';
import ProjectsManagement from './pages/mentor/project-management';
import ProjectDetail from './pages/mentor/project-details';
const App = () => {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/signup", element: _jsx(SignUpSelection, {}) }), _jsx(Route, { path: "/signup/student", element: _jsx(StudentSignUp, {}) }), _jsx(Route, { path: "/signup/professor", element: _jsx(ProfessorSignUp, {}) }), _jsx(Route, { path: "/verifyEmail", element: _jsx(Otp, {}) }), _jsx(Route, { path: "/application", element: _jsx(Application, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPassword, {}) }), _jsx(Route, { path: "/reset-password", element: _jsx(ResetPassword, {}) }), _jsxs(Route, { element: _jsx(DashboardLayout, {}), children: [_jsx(Route, { path: "/dashboard", element: _jsx("div", { children: "Dashboard Page" }) }), _jsx(Route, { path: "/progress", element: _jsx(Progress, { projectId: "default-project-id" }) }), _jsx(Route, { path: "/team", element: _jsx(Team, {}) }), _jsx(Route, { path: "/training", element: _jsx(Training, {}) }), _jsx(Route, { path: "/support", element: _jsx("div", { children: "Support Page" }) }), _jsx(Route, { path: "/settings", element: _jsx("div", { children: "Settings Page" }) })] }), _jsx(Route, { path: "/mentor/projects-management", element: _jsx(ProjectsManagement, {}) }), _jsx(Route, { path: "/mentor/projects/:projectId", element: _jsx(ProjectDetail, {}) })] }));
};
export default App;
